// app/javascript/controllers/index.js
// This file is auto-generated by ./bin/rails stimulus:manifest:update

import { application } from "./application"

import HelloController from "./hello_controller"
import NavController from "./nav_controller"
import InfiniteScrollController from "./infinite_scroll_controller"

application.register("hello", HelloController)
application.register("nav",   NavController)
application.register("infinite-scroll", InfiniteScrollController)
